name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: code
        uses: actions/checkout@v3

      - name: set up
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame coverage coveralls
          
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.4
            
      - name: Run tests with coverage
        run: |
          coverage run --rcfile=.coveragerc -m unittest discover -s . -p "test_game.py"
          coverage report

      - name: Coveralls
        run: |
          coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{cCOyiKhJzoiowaBtTUKxrOSNzi1GHPiqS}}
